"""
============================================================
BOUSLA - AI Career Advisor
------------------------------------------------------------
Analysis Response Schema

Purpose:
Defines the structure of the response returned by the
AI analysis endpoint.

Responsibilities:
- Ensure consistent API responses.
- Validate the AI analysis structure.
- Improve Swagger documentation.

Author:
BOUSLA Development Team
============================================================
"""

from pydantic import BaseModel
from typing import List


# ------------------------------------------------------------
# AI Analysis Schema
#
# Represents the complete analysis generated by the AI.
# ------------------------------------------------------------
class StudentAnalysis(BaseModel):

    summary: str

    riasecInterpretation: str

    bigFiveInterpretation: str

    workValuesInterpretation: str

    skillsInterpretation: str

    careerGoalsInterpretation: str

    strengths: List[str]

    developmentAreas: List[str]

    learningStyle: str

    idealWorkEnvironment: str

    confidenceLevel: str


# ------------------------------------------------------------
# API Response Schema
#
# Represents the response returned to the frontend.
# ------------------------------------------------------------
class AnalysisResponse(BaseModel):

    success: bool

    analysis: StudentAnalysis